config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/tables')

  resource :session, only: %i[new create destroy]
  get "/tables", to: "tables#index"

  resources :actors_groups, path: "/tables/actorsGroups"
  resources :actors, path: "/tables/actors"
  resources :instruments_groups, path: "/tables/instrumentsGroups"
  resources :instruments, path: "/tables/instruments"
  resources :domains, path: "/tables/domains"
  resources :competences, path: "/tables/competences"

  # Default route (if unknown url)
  match "*path" => redirect("/tables"), via: [:get, :post]
end

app/models/actor.rb
class Actor < ApplicationRecord
  belongs_to :actors_group, optional: true

  before_validation :strip_blanks

  validates_presence_of :name, :message => 'Le nom de l\'acteur doit être spécifié.'
  validates_uniqueness_of :name, :case_sensitive => false, :message => 'Le nom de l\'acteur est déjà utilisé.'
  validates_length_of :name, :maximum => 250, :message => 'Le nom de l\'acteur doit avoir maximum 250 caractères.'
  validates_length_of :abbreviation, :maximum => 20, :message => 'L\'abréviation de l\'acteur doit avoir maximum 20 caractères.'
  validates_length_of :country, :maximum => 20, :message => 'Le pays de l\'acteur doit avoir maximum 20 caractères.'
  validates_length_of :phone, :maximum => 20, :message => 'Le numéro de téléphone de l\'acteur doit avoir maximum 20 caractères.'
  validates_numericality_of :actors_group_id, :greater_than_or_equal_to => 0, :message => 'Choisir une catégorie d\'acteurs pour cet acteur.'

  def strip_blanks
    self.name = self.name.strip
    self.abbreviation = self.abbreviation.strip
    self.country = self.country.strip
    self.phone = self.phone.strip
    self.link = self.link.strip
  end
end

app/controllers/actors_controller.rb
class ActorsController < AuthenticateController
  before_action :set_actor, only: [:show, :edit, :update, :destroy]

  # GET /actors
  # GET /actors.json
  def index
    @actors = Actor.all.order(updated_at: :desc)
  end

  # GET /actors/1
  # GET /actors/1.json
  def show
  end

  # GET /actors/new
  def new
    @actor = Actor.new
  end

  # GET /actors/1/edit
  def edit
  end

  # POST /actors
  # POST /actors.json
  def create
    @actor = Actor.new(actor_params)

    respond_to do |format|
      if @actor.save
        format.html { redirect_to @actor, notice: 'L\'acteur a été créé.' }
        format.json { render :show, status: :created, location: @actor }
      else
        format.html { render :new }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actors/1
  # PATCH/PUT /actors/1.json
  def update
    respond_to do |format|
      if @actor.update(actor_params)
        format.html { redirect_to @actor, notice: 'L\'acteur a été mis à jour.' }
        format.json { render :show, status: :ok, location: @actor }
      else
        format.html { render :edit }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actors/1
  # DELETE /actors/1.json
  def destroy
    @actor.destroy
    respond_to do |format|
      format.html { redirect_to actors_url, notice: 'L\'acteur a été supprimé.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_actor
      @actor = Actor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def actor_params
      params.require(:actor).permit(:name, :abbreviation, :country, :phone, :link, :actors_group_id)
    end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/views/actors/_form.html.erb
<%= form_with(model: actor, local: true) do |form| %>
  <% if actor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(actor.errors.count, "erreur identifiée", "erreurs identifiées") %> : </h2>

      <ul>
      <% actor.errors.messages.values.each do |message| %>
        <li><%= message[0] %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <hr/><h3>Informations sur l'acteur</h3><br/>

  <div class="field">
    Nom de l'acteur* : <br/>
    <em>Champ de type texte (maximum 250 caractères, espaces compris) et champ à valeur unique</em><br/>
    <%= form.text_field :name, size: '43.5' %>
  </div><br/>

  <div class="field">
    Abréviation de l'acteur : <br/>
    <em>Champ de type texte (maximum 20 caractères, espaces compris)</em><br/>
    <%= form.text_field :abbreviation, size: '10' %>
  </div><br/>

  <div class="field">
    Pays de l'acteur : <br/>
    <em>Champ de type texte (maximum 20 caractères, espaces compris)</em><br/>
    <%= form.text_field :country, size: '10' %>
  </div><br/>

  <div class="field">
    Téléphone de l'acteur : <br/>
    <em>Champ de type texte (maximum 20 caractères, espaces compris)</em><br/>
    <%= form.text_field :phone, size: '10' %>
  </div><br/>

  <div class="field">
    Site Web de l'acteur : <br/>
    <em>Champ de type texte (nombre illimité de caractères)</em><br/>
    <%= form.text_field :link, size: '43.5' %>
  </div><br/>

  <hr/><h3>Classification de l'acteur</h3><br/>

  <div class="field">
    Catégorie d'acteurs* : <br/>
    <em>Champ obligatoire (l'acteur doit appartenir à une des catégories d'acteurs)</em><br/>
    <%= form.select :actors_group_id, ActorsGroup.all.collect { |group| [group.name, group.id] }, { :include_blank => "Choisir" } %>
    <%= link_to "Créer une nouvelle catégorie d'acteurs", new_actors_group_path %>
  </div><br/>

  <hr/>
  <h6>* Champs obligatoires</h6>
  <div class="actions">
    <%= form.submit "Enregistrer" %>
  </div>
<% end %>

app/views/actors/edit.html.erb
<h1>Modification d'un acteur</h1>

<%= render 'form', actor: @actor %>

<%= link_to 'Annuler', actors_path %>

app/views/actors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Acteurs</h1>
<em>
  Cette table contient l'ensemble des acteurs.
</em>

<hr/>
<%= link_to 'Ajouter un nouvel acteur', new_actor_path %>
<hr/>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Nom de l'acteur</th>
      <th>Abréviation de l'acteur</th>
      <th>Pays de l'acteur</th>
      <th>Téléphone de l'acteur</th>
      <th>Site Web de l'acteur</th>
      <th>Catégorie d'acteurs</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @actors.each do |actor| %>
      <tr>
        <td><%= actor.name %></td>
        <td><%= actor.abbreviation %></td>
        <td><%= actor.country %></td>
        <td><%= actor.phone %></td>
        <td><%= actor.link %></td>
        <td><%= actor.actors_group.name %></td>
        <td><%= link_to 'Editer', edit_actor_path(actor) %></td>
        <td><%= link_to 'Supprimer', actor, method: :delete, data: { confirm: 'Etes-vous sûr ? Attention : La suppression de cet acteur est irréversible.' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/actors/new.html.erb
<h1>Ajout d'un nouvel acteur</h1>

<%= render 'form', actor: @actor %>

<%= link_to 'Annuler', actors_path %>

app/views/actors/show.html.erb
<p id="notice"><%= notice %></p><br/>

<p>
  <strong>Nom de l'acteur : </strong>
  <%= @actor.name %>
</p>

<p>
  <strong>Abréviation de l'acteur : </strong>
  <%= @actor.abbreviation %>
</p>

<p>
  <strong>Pays de l'acteur : </strong>
  <%= @actor.country %>
</p>

<p>
  <strong>Téléphone de l'acteur : </strong>
  <%= @actor.phone %>
</p>

<p>
  <strong>Site Web de l'acteur : </strong>
  <%= @actor.link %>
</p>

<p>
  <strong>Catégorie d'acteurs : </strong>
  <%= @actor.actors_group.name %>
</p>

<br/>
<%= link_to 'Editer', edit_actor_path(@actor) %> |
<%= link_to 'Voir tous les acteurs', actors_path %>