config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/tables')

  resource :session, only: %i[new create destroy]
  get "/tables", to: "tables#index"

  resources :actors_groups, path: "/tables/actorsGroups"
  resources :actors, path: "/tables/actors"
  resources :instruments_groups, path: "/tables/instrumentsGroups"
  resources :instruments, path: "/tables/instruments"
  resources :domains, path: "/tables/domains"
  resources :competences, path: "/tables/competences"

  # Default route (if unknown url)
  match "*path" => redirect("/tables"), via: [:get, :post]
end

app/models/instruments_group.rb
class InstrumentsGroup < ApplicationRecord
  has_many :instruments, dependent: :destroy
  before_validation :strip_blanks

  validate :check_presence_namech_or_namefr
  validates_uniqueness_of :name_ch, :scope => :name_fr, :message => 'La combinaison nom suisse - nom français doit être unique.'
  validates_length_of :name_ch, :maximum => 250, :message => 'Le nom suisse de la catégorie d\'instruments doit avoir maximum 250 caractères.'
  validates_length_of :name_fr, :maximum => 250, :message => 'Le nom français de la catégorie d\'instruments doit avoir maximum 250 caractères.'
  validates_length_of :abbrev_ch, :maximum => 10, :message => 'L\'abréviation suisse de la catégorie d\'instruments doit avoir maximum 10 caractères.'
  validates_length_of :abbrev_fr, :maximum => 10, :message => 'L\'abréviation française de la catégorie d\'instruments doit avoir maximum 10 caractères.'
  validates_length_of :description, :maximum => 500, :message => 'La description de la catégorie d\'instruments doit avoir maximum 500 caractères.'
  validates_length_of :country, :maximum => 20, :message => 'Le pays de la catégorie d\'instruments doit avoir maximum 20 caractères.'
  validates_inclusion_of :kind, :in => [0, 1, 2, 3, 4], :message => 'Le type de la catégorie d\'instruments est incorrect.'
  validates_numericality_of :validity_period, :only_integer => true, :allow_blank => true, :greater_than_or_equal_to => 0, :message => 'La durée de validité doit être définie par un nombre entier positif (>= 0).'

  # Custom validation
  def check_presence_namech_or_namefr
    if self.name_ch == "" && self.name_fr == ""
      errors.add(:name_ch, "La catégorie d\'instruments doit avoir un nom suisse ou un nom français (ou les deux).")
    end
  end

  def strip_blanks
    self.name_ch = self.name_ch.strip
    self.name_fr = self.name_fr.strip
    self.abbrev_ch = self.abbrev_ch.strip
    self.abbrev_fr = self.abbrev_fr.strip
    self.description = self.description.strip
    self.country = self.country.strip
    self.descr_appeal_proc = self.descr_appeal_proc.strip
  end
end

app/controllers/instruments_groups_controller.rb
class InstrumentsGroupsController < AuthenticateController
  before_action :set_instruments_group, only: [:show, :edit, :update, :destroy]

  # GET /instruments_groups
  # GET /instruments_groups.json
  def index
    @instruments_groups = InstrumentsGroup.all.order(updated_at: :desc)
  end

  # GET /instruments_groups/1
  # GET /instruments_groups/1.json
  def show
  end

  # GET /instruments_groups/new
  def new
    @instruments_group = InstrumentsGroup.new
  end

  # GET /instruments_groups/1/edit
  def edit
  end

  # POST /instruments_groups
  # POST /instruments_groups.json
  def create
    @instruments_group = InstrumentsGroup.new(instruments_group_params)

    respond_to do |format|
      if @instruments_group.save
        format.html { redirect_to @instruments_group, notice: 'La catégorie d\'instruments a été créée.' }
        format.json { render :show, status: :created, location: @instruments_group }
      else
        format.html { render :new }
        format.json { render json: @instruments_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instruments_groups/1
  # PATCH/PUT /instruments_groups/1.json
  def update
    respond_to do |format|
      if @instruments_group.update(instruments_group_params)
        format.html { redirect_to @instruments_group, notice: 'La catégorie d\'instruments a été mise à jour.' }
        format.json { render :show, status: :ok, location: @instruments_group }
      else
        format.html { render :edit }
        format.json { render json: @instruments_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instruments_groups/1
  # DELETE /instruments_groups/1.json
  def destroy
    @instruments_group.destroy
    respond_to do |format|
      format.html { redirect_to instruments_groups_url, notice: 'La catégorie d\'instruments a été supprimée.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instruments_group
      @instruments_group = InstrumentsGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instruments_group_params
      params.require(:instruments_group).permit(:name_ch, :name_fr, :abbrev_ch, :abbrev_fr, :description, :country, :law, :appeal_proc, :descr_appeal_proc, :kind, :orientation, :prescriptive, :validity_period)
    end
end

app/helpers/instruments_groups_helper.rb
module InstrumentsGroupsHelper
end

app/views/instruments_groups/_form.html.erb
<%= form_with(model: instruments_group, local: true) do |form| %>
  <% if instruments_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(instruments_group.errors.count, "erreur identifiée", "erreurs identifiées") %> : </h2>

      <ul>
      <% instruments_group.errors.messages.values.each do |message| %>
        <li><%= message[0] %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <hr/><h3>Informations sur la catégorie d'instruments</h3><br/>

  <em>
    Nom suisse et nom français : au moins un des deux champs est obligatoire pour représenter la catégorie d'instruments.<br/>
    La combinaison nom suisse - nom français doit être unique.
  </em><br/><br/><br/>

  <div class="field">
    Nom suisse de la catégorie d'instruments : <br/>
    <em>Champ de type texte (maximum 250 caractères, espaces compris)</em><br/>
    <%= form.text_field :name_ch, size: '43.5' %>
  </div><br/>

  <div class="field">
    Nom français de la catégorie d'instruments : <br/>
    <em>Champ de type texte (maximum 250 caractères, espaces compris)</em><br/>
    <%= form.text_field :name_fr, size: '43.5' %>
  </div><br/>

  <div class="field">
    Abréviation suisse de la catégorie d'instruments : <br/>
    <em>Champ de type texte (maximum 10 caractères, espaces compris)</em><br/>
    <%= form.text_field :abbrev_ch, size: '10' %>
  </div><br/>

  <div class="field">
    Abréviation française de la catégorie d'instruments : <br/>
    <em>Champ de type texte (maximum 10 caractères, espaces compris)</em><br/>
    <%= form.text_field :abbrev_fr, size: '10' %>
  </div><br/>

  <div class="field">
    Description de la catégorie d'instruments : <br/>
    <em>Champ de type texte (maximum 500 caractères, espaces compris)</em><br/>
    <%= form.text_area :description, size: '40x5' %>
  </div><br/>

  <div class="field">
    Pays de la catégorie d'instruments : <br/>
    <em>Champ de type texte (maximum 20 caractères, espaces compris)</em><br/>
    <%= form.text_field :country, size: '10' %>
  </div><br/>

  <div class="field">
    Droit public ? 
    <%= form.check_box :law %>
  </div><br/>

  <div class="field">
    Procédure de recours ? 
    <%= form.check_box :appeal_proc %>
  </div><br/>

  <div class="field">
    Description de la procédure de recours : <br/>
    <em>Champ de type texte (nombre illimité de caractères)</em><br/>
    <%= form.text_area :descr_appeal_proc, size: '40x5' %>
  </div><br/>

  <div class="field">
    Type: <br/>
    <em>Champ de type liste déroulante (quatre choix possibles : plan, schéma, contrat, charte)</em><br/>
    <%= form.select :kind, options_for_select([["Choisir", 0], ["Plan", 1], ["Schéma", 2], ["Contrat", 3], ["Charte", 4]], selected: instruments_group.kind), id: :intruments_group_kind %>
  </div><br/>

  <div class="field">
    Orientation ?
    <%= form.check_box :orientation %>
  </div><br/>

  <div class="field">
    Prescriptif ?
    <%= form.check_box :prescriptive %>
  </div><br/>

  <div class="field">
    Durée de validité : <br/>
    <em>Champ de type nombre entier</em><br/>
    <%= form.text_field :validity_period, size: '10' %>
  </div><br/>

  <hr/>
  <div class="actions">
    <%= form.submit "Enregistrer" %>
  </div>
<% end %>

app/views/instruments_groups/edit.html.erb
<h1>Modification d'une catégorie d'instruments</h1>

<%= render 'form', instruments_group: @instruments_group %>

<%= link_to 'Annuler', instruments_groups_path %>

app/views/instruments_groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Catégories d'instruments</h1>
<em>
  Cette table contient l'ensemble des catégories d'instruments.
</em>

<hr/>
<%= link_to 'Ajouter une nouvelle catégorie d\'instruments', new_instruments_group_path %>
<hr/>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Nom suisse de la catégorie d'instruments</th>
      <th>Nom français de la catégorie d'instruments</th>
      <th>Abréviation suisse de la catégorie d'instruments</th>
      <th>Abréviation française de la catégorie d'instruments</th>
      <th>Description de la catégorie d'instruments</th>
      <th>Pays de la catégorie d'instruments</th>
      <th>Droit public ?</th>
      <th>Procédure de recours ?</th>
      <th>Description de la procédure de recours</th>
      <th>Type de la catégorie d'instruments</th>
      <th>Orientation ?</th>
      <th>Prescriptif ?</th>
      <th>Durée de validité</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% type = [["Aucun type", 0], ["Plan", 1], ["Schéma", 2], ["Contrat", 3], ["Charte", 4]] %>
    <% @instruments_groups.each do |instruments_group| %>
      <tr>
        <td><%= instruments_group.name_ch %></td>
        <td><%= instruments_group.name_fr %></td>
        <td><%= instruments_group.abbrev_ch %></td>
        <td><%= instruments_group.abbrev_fr %></td>
        <td><%= instruments_group.description %></td>
        <td><%= instruments_group.country %></td>
        <td>
          <% if instruments_group.law == true %>
            Oui
          <% else %>
            Non
          <% end %>
        </td>
        <td>
          <% if instruments_group.appeal_proc == true %>
            Oui
          <% else %>
            Non
          <% end %>
        </td>
        <td><%= instruments_group.descr_appeal_proc %></td>
        <td><%= type[instruments_group.kind][0] %></td>
        <td>
          <% if instruments_group.orientation == true %>
            Oui
          <% else %>
            Non
          <% end %>
        </td>
        <td>
          <% if instruments_group.prescriptive == true %>
            Oui
          <% else %>
            Non
          <% end %>
        </td>
        <td><%= instruments_group.validity_period %></td>
        <td><%= link_to 'Editer', edit_instruments_group_path(instruments_group) %></td>
        <td><%= link_to 'Supprimer', instruments_group, method: :delete, data: { confirm: 'Etes-vous sûr ? Attention : La suppression de cette catégorie d\'instruments est irréversible et supprimera tous les instruments associés.' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/instruments_groups/new.html.erb
<h1>Ajout d'une nouvelle catégorie d'instruments</h1>

<%= render 'form', instruments_group: @instruments_group %>

<%= link_to 'Annuler', instruments_groups_path %>

app/views/instruments_groups/show.html.erb
<p id="notice"><%= notice %></p><br/>
<% type = [["Aucun type", 0], ["Plan", 1], ["Schéma", 2], ["Contrat", 3], ["Charte", 4]] %>
<p>
  <strong>Nom suisse de la catégorie d'instruments : </strong>
  <%= @instruments_group.name_ch %>
</p>

<p>
  <strong>Nom français de la catégorie d'instruments : </strong>
  <%= @instruments_group.name_fr %>
</p>

<p>
  <strong>Abréviation suisse de la catégorie d'instruments : </strong>
  <%= @instruments_group.abbrev_ch %>
</p>

<p>
  <strong>Abréviation française de la catégorie d'instruments : </strong>
  <%= @instruments_group.abbrev_fr %>
</p>

<p>
  <strong>Description de la catégorie d'instruments : </strong>
  <%= @instruments_group.description %>
</p>

<p>
  <strong>Pays de la catégorie d'instruments : </strong>
  <%= @instruments_group.country %>
</p>

<p>
  <strong>Droit public ? </strong>
  <% if @instruments_group.law == true %>
    Oui
  <% else %>
    Non
  <% end %>
</p>

<p>
  <strong>Procédure de recours ? </strong>
  <% if @instruments_group.appeal_proc == true %>
    Oui
  <% else %>
    Non
  <% end %>
</p>

<p>
  <strong>Description de la procédure de recours : </strong>
  <%= @instruments_group.descr_appeal_proc %>
</p>

<p>
  <strong>Type de la catégorie d'instruments : </strong>
  <%= type[@instruments_group.kind][0] %>
</p>

<p>
  <strong>Orientation ? </strong>
  <% if @instruments_group.orientation == true %>
    Oui
  <% else %>
    Non
  <% end %>
</p>

<p>
  <strong>Prescriptif ? </strong>
  <% if @instruments_group.prescriptive == true %>
    Oui
  <% else %>
    Non
  <% end %>
</p>

<p>
  <strong>Durée de validité : </strong>
  <%= @instruments_group.validity_period %>
</p>

<br/>
<%= link_to 'Editer', edit_instruments_group_path(@instruments_group) %> |
<%= link_to 'Voir toutes les catégories d\'instruments', instruments_groups_path %>