config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/tables')

  resource :session, only: %i[new create destroy]
  get "/tables", to: "tables#index"

  resources :actors_groups, path: "/tables/actorsGroups"
  resources :actors, path: "/tables/actors"
  resources :instruments_groups, path: "/tables/instrumentsGroups"
  resources :instruments, path: "/tables/instruments"
  resources :domains, path: "/tables/domains"
  resources :competences, path: "/tables/competences"

  # Default route (if unknown url)
  match "*path" => redirect("/tables"), via: [:get, :post]
end

app/controllers/tables_controller.rb
class TablesController < AuthenticateController
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/tables/index.html.erb
<br/><p id="notice"><%= notice %></p>
<h1>Liste des tables</h1><hr/>

<table class="table table-striped table-bordered table-hover" style="max-width: 30%">
  <tr>
    <td>Table des domaines d'actions</td>
    <td><%= link_to 'Voir', domains_path %></td>
  </tr>
  <tr>
    <td>Table des champs de compétences</td>
    <td><%= link_to 'Voir', competences_path %></td>
  </tr>
  <tr>
    <td>Table des catégories d'acteurs</td>
    <td><%= link_to 'Voir', actors_groups_path %></td>
  </tr>
  <tr>
    <td>Table des acteurs</td>
    <td><%= link_to 'Voir', actors_path %></td>
  </tr>
  <tr>
    <td>Table des catégories d'instruments</td>
    <td><%= link_to 'Voir', instruments_groups_path %></td>
  </tr>
  <tr>
    <td>Table des instruments territoriaux</td>
    <td><%= link_to 'Voir', instruments_path %></td>
  </tr>
</table>