config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/tables')

  resource :session, only: %i[new create destroy]
  get "/tables", to: "tables#index"

  resources :actors_groups, path: "/tables/actorsGroups"
  resources :actors, path: "/tables/actors"
  resources :instruments_groups, path: "/tables/instrumentsGroups"
  resources :instruments, path: "/tables/instruments"
  resources :domains, path: "/tables/domains"
  resources :competences, path: "/tables/competences"

  # Default route (if unknown url)
  match "*path" => redirect("/tables"), via: [:get, :post]
end

app/models/instrument.rb
class Instrument < ApplicationRecord
  belongs_to :instruments_group, optional: true

  before_validation :strip_blanks

  validates_presence_of :name, :message => 'Le nom de l\'instrument doit être spécifié.'
  validates_uniqueness_of :name, :case_sensitive => false, :message => 'Le nom de l\'instrument est déjà utilisé.'
  validates_length_of :name, :maximum => 250, :message => 'Le nom de l\'instrument doit avoir maximum 250 caractères.'
  validates_length_of :abbreviation, :maximum => 10, :message => 'L\'abréviation de l\'instrument doit avoir maximum 10 caractères.'
  validates_length_of :description, :maximum => 500, :message => 'La description de l\'instrument doit avoir maximum 500 caractères.'
  validates_numericality_of :instruments_group_id, :greater_than_or_equal_to => 0, :message => 'Choisir une catégorie d\'instruments pour cet instrument.'

  def strip_blanks
    self.name = self.name.strip
    self.abbreviation = self.abbreviation.strip
    self.description = self.description.strip
    self.planning = self.planning.strip
    self.transboundary = self.transboundary.strip
    self.descr_appeal_proc = self.descr_appeal_proc.strip
  end
end

app/controllers/instruments_controller.rb
class InstrumentsController < AuthenticateController
  before_action :set_instrument, only: [:show, :edit, :update, :destroy]

  # GET /instruments
  # GET /instruments.json
  def index
    @instruments = Instrument.all.order(updated_at: :desc)
  end

  # GET /instruments/1
  # GET /instruments/1.json
  def show
  end

  # GET /instruments/new
  def new
    @instrument = Instrument.new
  end

  # GET /instruments/1/edit
  def edit
  end

  # POST /instruments
  # POST /instruments.json
  def create
    @instrument = Instrument.new(instrument_params)

    respond_to do |format|
      if @instrument.save
        format.html { redirect_to @instrument, notice: 'L\'instrument a été créé.' }
        format.json { render :show, status: :created, location: @instrument }
      else
        format.html { render :new }
        format.json { render json: @instrument.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instruments/1
  # PATCH/PUT /instruments/1.json
  def update
    respond_to do |format|
      if @instrument.update(instrument_params)
        format.html { redirect_to @instrument, notice: 'L\'instrument a été mis à jour.' }
        format.json { render :show, status: :ok, location: @instrument }
      else
        format.html { render :edit }
        format.json { render json: @instrument.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instruments/1
  # DELETE /instruments/1.json
  def destroy
    @instrument.destroy
    respond_to do |format|
      format.html { redirect_to instruments_url, notice: 'L\'instrument a été supprimé.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instrument
      @instrument = Instrument.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instrument_params
      params.require(:instrument).permit(:name, :abbreviation, :start_date, :last_rev_date, :description, :planning, :transboundary, :appeal_proc, :descr_appeal_proc, :under_revision_since, :instruments_group_id)
    end
end

app/helpers/instruments_helper.rb
module InstrumentsHelper
end

app/views/instruments/_form.html.erb
<%= form_with(model: instrument, local: true) do |form| %>
  <% if instrument.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(instrument.errors.count, "erreur identifiée", "erreurs identifiées") %> : </h2>

      <ul>
      <% instrument.errors.messages.values.each do |message| %>
        <li><%= message[0] %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <hr/><h3>Informations sur l'instrument territorial</h3><br/>

  <div class="field">
    Nom de l'instrument* : <br/>
    <em>Champ de type texte (maximum 250 caractères, espaces compris) et champ à valeur unique</em><br/>
    <%= form.text_field :name, size: '43.5' %>
  </div><br/>

  <div class="field">
    Abréviation de l'instrument : <br/>
    <em>Champ de type texte (maximum 10 caractères, espaces compris)</em><br/>
    <%= form.text_field :abbreviation, size: '10' %>
  </div><br/>

  <div class="field">
    Date d'entrée en vigueur de l'instrument : <br/>
    <%= form.date_select :start_date, :order => [:day, :month, :year], :start_year => Date.today.year, :end_year => 1700, :use_two_digit_numbers => true, prompt: { day: 'Choisir le jour', month: 'Choisir le mois', year: 'Choisir l\'année' } %>
  </div><br/>

  <div class="field">
    Date de dernière révision de l'instrument : <br/>
    <%= form.date_select :last_rev_date, :order => [:day, :month, :year], :start_year => Date.today.year, :end_year => 1700, :use_two_digit_numbers => true, prompt: { day: 'Choisir le jour', month: 'Choisir le mois', year: 'Choisir l\'année' } %>
  </div><br/>

  <div class="field">
    Description de l'instrument : <br/>
    <em>Champ de type texte (maximum 500 caractères, espaces compris)</em><br/>
    <%= form.text_area :description, size: '40x5' %>
  </div><br/>

  <div class="field">
    Contenu "Aménagement du territoire" : <br/>
    <em>Champ de type texte (nombre illimité de caractères)</em><br/>
    <%= form.text_area :planning, size: '40x5' %>
  </div><br/>

  <div class="field">
    Contenu "Transfrontalier" : <br/>
    <em>Champ de type texte (nombre illimité de caractères)</em><br/>
    <%= form.text_area :transboundary, size: '40x5' %>
  </div><br/>

  <div class="field">
    Procédure de recours ? 
    <%= form.check_box :appeal_proc %>
  </div><br/>

  <div class="field">
    Description de la procédure de recours : <br/>
    <em>Champ de type texte (nombre illimité de caractères)</em><br/>
    <%= form.text_area :descr_appeal_proc, size: '40x5' %>
  </div><br/>

  <div class="field">
    En révision depuis (date de début) : <br/>
    <%= form.date_select :under_revision_since, :order => [:day, :month, :year], :start_year => Date.today.year, :end_year => 1700, :use_two_digit_numbers => true, prompt: { day: 'Choisir le jour', month: 'Choisir le mois', year: 'Choisir l\'année' } %>
  </div><br/>

  <hr/><h3>Classification de l'instrument</h3><br/>

  <div class="field">
    Catégorie d'instruments* : <br/>
    <em>Champ obligatoire (l'instrument territorial doit appartenir à une des catégories d'instruments)</em><br/>
    <% categories = InstrumentsGroup.all %>
    <% catoptions = Array.new %>
    <% catselected = '' %>
    <% type = request.path_info.split("/")[4] %>
    <% categories.each do |category| %>
      <% if category.name_ch != "" and category.name_fr != "" %>
        <% catarray = [category.name_ch + " (ch) / " + category.name_fr + " (fr)", category.id] %>
      <% elsif category.name_ch != "" and category.name_fr == "" %>
        <% catarray = [category.name_ch + " (ch) / - (fr)", category.id] %>
      <% elsif category.name_ch == "" and category.name_fr != "" %>
        <% catarray = ["- (ch) / " + category.name_fr + " (fr)", category.id] %>
      <% else %>
        <% catarray = ["???", category.id] %>
      <% end %>
      <% catoptions.push(catarray) %>
      <% if type == "edit" %>
        <% if category.id == instrument.instruments_group_id %>
          <% catselected = category.id %>
        <% end %>
      <% end %>
    <% end %>
    <% if type == "edit" %>
      <%= form.select :instruments_group_id, options_for_select(catoptions, selected: catselected), id: :instruments_group_id %>
    <% else %>
      <% catoptions.unshift(["Choisir", -1]) %>
      <%= form.select :instruments_group_id, options_for_select(catoptions), id: :instruments_group_id %>
    <% end %>
    <%= link_to "Créer une nouvelle catégorie d'instruments", new_instruments_group_path %>
  </div><br/>

  <hr/>
  <h6>* Champs obligatoires</h6>
  <div class="actions">
    <%= form.submit "Enregistrer" %>
  </div>
<% end %>

app/views/instruments/edit.html.erb
<h1>Modification d'un instrument territorial</h1>

<%= render 'form', instrument: @instrument %>

<%= link_to 'Annuler', instruments_path %>

app/views/instruments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Instruments territoriaux</h1>
<em>
  Cette table contient l'ensemble des instruments territoriaux.
</em>

<hr/>
<%= link_to 'Ajouter un nouvel instrument territorial', new_instrument_path %>
<hr/>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Nom de l'instrument</th>
      <th>Abréviation de l'instrument</th>
      <th>Date d'entrée en vigueur de l'instrument</th>
      <th>Date de dernière révision de l'instrument</th>
      <th>Description de l'instrument</th>
      <th>Contenu "Aménagement du territoire"</th>
      <th>Contenu "Transfrontalier"</th>
      <th>Procédure de recours ?</th>
      <th>Description de la procédure de recours</th>
      <th>En révision depuis (date de début)</th>
      <th>Catégorie d'instruments</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @instruments.each do |instrument| %>
      <tr>
        <td><%= instrument.name %></td>
        <td><%= instrument.abbreviation %></td>
        <td>
          <% if instrument.start_date != nil %>
            <%= instrument.start_date.strftime("%d.%m.%Y") %>
          <% end %>
        </td>
        <td>
          <% if instrument.last_rev_date != nil %>
            <%= instrument.last_rev_date.strftime("%d.%m.%Y") %>
          <% end %>
        </td>
        <td><%= instrument.description %></td>
        <td><%= instrument.planning %></td>
        <td><%= instrument.transboundary %></td>
        <td>
          <% if instrument.appeal_proc == true %>
            Oui
          <% else %>
            Non
          <% end %>
        </td>
        <td><%= instrument.descr_appeal_proc %></td>
        <td>
          <% if instrument.under_revision_since != nil %>
            <%= instrument.under_revision_since.strftime("%d.%m.%Y") %>
          <% end %>
        </td>
        <td>
          <% if instrument.instruments_group.name_ch != "" %>
            <%= instrument.instruments_group.name_ch %> (ch) 
          <% end %>
          <% if instrument.instruments_group.name_ch != "" and instrument.instruments_group.name_fr != "" %>
            /
          <% end %>
          <% if instrument.instruments_group.name_fr != "" %>
            <%= instrument.instruments_group.name_fr %> (fr)
          <% end %>
        </td>
        <td><%= link_to 'Editer', edit_instrument_path(instrument) %></td>
        <td><%= link_to 'Supprimer', instrument, method: :delete, data: { confirm: 'Etes-vous sûr ? Attention : La suppression de cet instrument territorial est irréversible.' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/instruments/new.html.erb
<h1>Ajout d'un nouvel instrument territorial</h1>

<%= render 'form', instrument: @instrument %>

<%= link_to 'Annuler', instruments_path %>

app/views/instruments/show.html.erb
<p id="notice"><%= notice %></p><br/>

<p>
  <strong>Nom de l'instrument : </strong>
  <%= @instrument.name %>
</p>

<p>
  <strong>Abréviation de l'instrument : </strong>
  <%= @instrument.abbreviation %>
</p>

<p>
  <strong>Date d'entrée en vigueur de l'instrument : </strong>
  <% if @instrument.start_date != nil %>
    <%= @instrument.start_date.strftime("%d.%m.%Y") %>
  <% end %>
</p>

<p>
  <strong>Date de dernière révision de l'instrument : </strong>
  <% if @instrument.last_rev_date != nil %>
    <%= @instrument.last_rev_date.strftime("%d.%m.%Y") %>
  <% end %>
</p>

<p>
  <strong>Description de l'instrument : </strong>
  <%= @instrument.description %>
</p>

<p>
  <strong>Contenu "Aménagement du territoire" : </strong>
  <%= @instrument.planning %>
</p>

<p>
  <strong>Contenu "Transfrontalier" : </strong>
  <%= @instrument.transboundary %>
</p>

<p>
  <strong>Procédure de recours ? </strong>
  <% if @instrument.appeal_proc == true %>
    Oui
  <% else %>
    Non
  <% end %>
</p>

<p>
  <strong>Description de la procédure de recours : </strong>
  <%= @instrument.descr_appeal_proc %>
</p>

<p>
  <strong>En révision depuis (date de début) : </strong>
  <% if @instrument.under_revision_since != nil %>
    <%= @instrument.under_revision_since.strftime("%d.%m.%Y") %>
  <% end %>
</p>

<p>
  <strong>Catégorie d'instruments : </strong>
  <% if @instrument.instruments_group.name_ch != "" %>
    <%= @instrument.instruments_group.name_ch %> (ch) 
  <% end %>
  <% if @instrument.instruments_group.name_ch != "" and @instrument.instruments_group.name_fr != "" %>
    /
  <% end %>
  <% if @instrument.instruments_group.name_fr != "" %>
    <%= @instrument.instruments_group.name_fr %> (fr)
  <% end %>
</p>

<br/>
<%= link_to 'Editer', edit_instrument_path(@instrument) %> |
<%= link_to 'Voir tous les instruments territoriaux', instruments_path %>